Repository pluralsh/plural-artifacts, pull requests merged in 2023-07, with the labels that each got.

#759 fix(rabbitmq): rabbitmq notes
  rabbitmq/plural/notes.tpl
  rabbitmq/repository.yaml
Labels: documentation

#767 ci: fix installing commit analyzer
  .github/workflows/matrix-vendor-and-publish.yml
Labels: hotfix

#775 Support external ingress for elasticsearch too
  elasticsearch/helm/elasticsearch/Chart.yaml
  elasticsearch/helm/elasticsearch/templates/es-ingess.yaml
  elasticsearch/helm/elasticsearch/values.yaml
  elasticsearch/plural/docs/external-ingress.md
  elasticsearch/repository.yaml
Labels: enhancement

#778 feat: Upgrade n8n to v0.236
  n8n/helm/n8n/Chart.lock
  n8n/helm/n8n/Chart.yaml
  n8n/helm/n8n/charts/n8n-0.10.0.tgz
  n8n/helm/n8n/charts/test-base-0.1.10.tgz
  n8n/helm/n8n/values.yaml
Labels: enhancement

#782 Upgrade metabase to v0.46.6 and add path image to vendor list
  metabase/helm/metabase/Chart.yaml
  metabase/helm/metabase/values.yaml
  metabase/vendor_images.yaml
Labels: enhancement, hotfix

#783 fix: Upgrade to v0.46.6.1
  metabase/helm/metabase/Chart.yaml
  metabase/helm/metabase/values.yaml
Labels: enhancement, hotfix

#779 feat: Add docs for mlflow basic auth
  mlflow/plural/docs/basic-auth.md
  mlflow/repository.yaml
Labels: documentation

#780 feat: Upgrade airbyte to 0.50.8
  airbyte/helm/airbyte/Chart.yaml
  airbyte/helm/airbyte/values.yaml
  sentry/helm/sentry/Chart.yaml
  sentry/helm/sentry/values.yaml
Labels: enhancement

#784 feat: Support mlflow object versioning
  mlflow/plural/docs/bucket-versioning.md
  mlflow/terraform/aws/deps.yaml
  mlflow/terraform/aws/main.tf
  mlflow/terraform/aws/variables.tf
Labels: enhancement

#789 feat: publish cubejs to BETA
  cube/repository.yaml
  cube/terraform/aws/deps.yaml
  cube/terraform/aws/iam.tf
  imgproxy/repository.yaml
  neo4j/repository.yaml
Labels: enhancement

#786 Double posthog plugin mem limit
  posthog/helm/posthog/Chart.yaml
  posthog/helm/posthog/values.yaml
Labels: bug

#790 feat: Upgrade kubescape
  kubescape/helm/kubescape/Chart.lock
  kubescape/helm/kubescape/Chart.yaml
  kubescape/helm/kubescape/charts/armo-cluster-components-1.7.8.tgz
  kubescape/helm/kubescape/charts/kubescape-cloud-operator-1.14.2.tgz
  kubescape/helm/kubescape/values.yaml.tpl
Labels: enhancement
