Repository pluralsh/plural-artifacts, pull requests merged in 2023-03, with the labels that each got.

#538 Use newer gke version
  bootstrap/terraform/gcp-bootstrap/deps.yaml
  bootstrap/terraform/gcp-bootstrap/variables.tf
Labels: bug

#539 Add readme
  Makefile
  README.md
Labels: documentation, enhancement

#540 some readme polish
  README.md
Labels: documentation

#559 fix mongodb deps
  mongodb/terraform/kube/deps.yaml
Labels: bug

#564 Fix GCP gitlab setup
  gitlab/helm/gitlab/Chart.yaml
  gitlab/helm/gitlab/values.yaml.tpl
  gitlab/plural/notes.tpl
  gitlab/terraform/gcp/deps.yaml
  gitlab/terraform/gcp/main.tf
Labels: bug

#575 Add docs for clickhouse setup
  clickhouse/plural/docs/exposing-via-loadbalancer.md
  clickhouse/plural/docs/setup.md
  clickhouse/repository.yaml
Labels: documentation

#579 Upgrade airbyte to v0.42.0
  airbyte/helm/airbyte/Chart.yaml
  airbyte/helm/airbyte/values.yaml
  airflow/helm/airflow/Chart.yaml
  airflow/helm/airflow/values.yaml.tpl
Labels: enhancement

#584 Upgrade chatwoot
  chatwoot/helm/chatwoot/Chart.lock
  chatwoot/helm/chatwoot/Chart.yaml
  chatwoot/helm/chatwoot/charts/chatwoot-1.0.17.tgz
  chatwoot/helm/chatwoot/charts/chatwoot-1.0.8.tgz
  chatwoot/helm/chatwoot/values.yaml
Labels: enhancement

#595 Don't set known hosts by default for airflow
  airflow/helm/airflow/Chart.yaml
  airflow/helm/airflow/values.yaml.tpl
  sentry/terraform/gcp/deps.yaml
  sentry/terraform/gcp/main.tf
Labels: bug

#602 Add loki ingress dependency
  loki/helm/loki/Chart.yaml
  loki/helm/loki/deps.yaml
  loki/plural/recipes/loki-aws.yaml
  loki/plural/recipes/loki-azure.yaml
  loki/plural/recipes/loki-gcp.yaml
Labels: bug

#603 Don't ask for redis hosts in recipe
  redis/plural/docs/external-hostname.md
  redis/plural/recipes/aws-redis.yaml
  redis/plural/recipes/azure-redis.yaml
  redis/plural/recipes/gcp-redis.yaml
  redis/repository.yaml
Labels: documentation, enhancement
