Repository pluralsh/plural-artifacts, pull requests merged in 2023-10, with the labels that each got.

#862 feat: upgrade capi components + aws provider
  bootstrap/helm/cluster-api-bootstrap/Chart.lock
  bootstrap/helm/cluster-api-bootstrap/Chart.yaml
  bootstrap/helm/cluster-api-bootstrap/charts/cluster-api-bootstrap-0.1.6.tgz
  bootstrap/helm/cluster-api-bootstrap/charts/cluster-api-bootstrap-0.1.7.tgz
  bootstrap/helm/cluster-api-control-plane/Chart.lock
  bootstrap/helm/cluster-api-control-plane/Chart.yaml
  bootstrap/helm/cluster-api-control-plane/charts/cluster-api-control-plane-0.1.6.tgz
  bootstrap/helm/cluster-api-control-plane/charts/cluster-api-control-plane-0.1.7.tgz
  bootstrap/helm/cluster-api-core/Chart.lock
  bootstrap/helm/cluster-api-core/Chart.yaml
  bootstrap/helm/cluster-api-core/charts/cluster-api-core-0.1.7.tgz
  bootstrap/helm/cluster-api-core/charts/cluster-api-core-0.1.8.tgz
  bootstrap/helm/cluster-api-provider-aws/Chart.lock
  bootstrap/helm/cluster-api-provider-aws/Chart.yaml
  bootstrap/helm/cluster-api-provider-aws/charts/cluster-api-provider-aws-0.1.11.tgz
  bootstrap/helm/cluster-api-provider-aws/charts/cluster-api-provider-aws-0.1.9.tgz
  bootstrap/helm/cluster-api-provider-aws/values.yaml
  bootstrap/terraform/aws-bootstrap/variables.tf
Labels: dependencies

#859 feat(bootstrap): add knobs to set control plane network setup and encryption config
  bootstrap/helm/bootstrap/Chart.lock
  bootstrap/helm/bootstrap/Chart.yaml
  bootstrap/helm/bootstrap/charts/aws-load-balancer-controller-1.4.8.tgz
  bootstrap/helm/bootstrap/charts/aws-load-balancer-controller-1.6.1.tgz
  bootstrap/helm/bootstrap/values.yaml
  bootstrap/terraform/aws-bootstrap/deps.yaml
  bootstrap/terraform/aws-bootstrap/main.tf
  bootstrap/terraform/aws-bootstrap/variables.tf
Labels: enhancement

#852 feat: Switch to official v1.11 CAPZ image
  bootstrap/helm/cluster-api-cluster/Chart.yaml
  bootstrap/helm/cluster-api-cluster/templates/azure/control-plane.yaml
  bootstrap/helm/cluster-api-cluster/values.yaml
  bootstrap/helm/cluster-api-provider-azure/Chart.lock
  bootstrap/helm/cluster-api-provider-azure/Chart.yaml
  bootstrap/helm/cluster-api-provider-azure/charts/cluster-api-provider-azure-0.1.15.tgz
  bootstrap/helm/cluster-api-provider-azure/charts/cluster-api-provider-azure-0.1.8.tgz
  bootstrap/helm/cluster-api-provider-azure/scripts/Makefile
  bootstrap/helm/cluster-api-provider-azure/templates/azurecluster-crd.yaml
  bootstrap/helm/cluster-api-provider-azure/templates/azureclusteridentity-crd.yaml
  bootstrap/helm/cluster-api-provider-azure/templates/azureclustertemplate-crd.yaml
  bootstrap/helm/cluster-api-provider-azure/templates/azureidentity-crd.yaml
  bootstrap/helm/cluster-api-provider-azure/templates/azureidentitybinding-crd.yaml
  bootstrap/helm/cluster-api-provider-azure/templates/azuremachine-crd.yaml
  bootstrap/helm/cluster-api-provider-azure/templates/azuremachinepool-crd.yaml
  bootstrap/helm/cluster-api-provider-azure/templates/azuremachinepoolmachine-crd.yaml
  bootstrap/helm/cluster-api-provider-azure/templates/azuremachinetemplate-crd.yaml
  bootstrap/helm/cluster-api-provider-azure/templates/azuremanagedcluster-crd.yaml
  bootstrap/helm/cluster-api-provider-azure/templates/azuremanagedcontrolplane-crd.yaml
  bootstrap/helm/cluster-api-provider-azure/templates/azuremanagedmachinepool-crd.yaml
  bootstrap/helm/cluster-api-provider-azure/templates/azurepodidentityexception-crd.yaml
  bootstrap/helm/cluster-api-provider-azure/templates/job.yaml
  bootstrap/helm/cluster-api-provider-azure/values.yaml
  bootstrap/helm/cluster-api-provider-azure/values.yaml.tpl
  bootstrap/terraform/azure-bootstrap/deps.yaml
  bootstrap/terraform/azure-bootstrap/main.tf
Labels: roadmap

#880 feat: Update airbyte to 0.50.33
  airbyte/helm/airbyte/Chart.yaml
  airbyte/helm/airbyte/charts/airbyte-0.43.22.tgz
  airbyte/helm/airbyte/values.yaml
Labels: enhancement
