Repository pluralsh/plural-artifacts, pull requests merged in 2023-01, with the labels that each got.

#478 Add correct uriFormats for gitlab
  gitlab/plural/recipes/aws-gitlab.yaml
  gitlab/plural/recipes/gcp-gitlab.yaml
  gitlab/repository.yaml
Labels: enhancement

#483 Expose GKE release channel in gcp bootstrap
  bootstrap/terraform/gcp-bootstrap/deps.yaml
  bootstrap/terraform/gcp-bootstrap/main.tf
  bootstrap/terraform/gcp-bootstrap/variables.tf
Labels: enhancement

#484 Add ability to toggle between regional/zonal gke clusters
  bootstrap/terraform/gcp-bootstrap/deps.yaml
  bootstrap/terraform/gcp-bootstrap/main.tf
  bootstrap/terraform/gcp-bootstrap/variables.tf
Labels: enhancement

#487 Add app docs for airflow, airbyte, superset
  .github/workflows/matrix-vendor-and-publish.yml
  airbyte/plural/docs/basic-auth.md
  airbyte/plural/docs/bring-your-own-db.md
  airbyte/repository.yaml
  airflow/plural/docs/bring-your-db.md
  airflow/plural/docs/pip-packages.md
  airflow/repository.yaml
  superset/plural/docs/pip-packages.md
  superset/repository.yaml
Labels: documentation, enhancement

#490 increase airbyte db max connections
  airbyte/helm/airbyte/Chart.lock
  airbyte/helm/airbyte/Chart.yaml
  airbyte/helm/airbyte/charts/postgres-0.1.11.tgz
  airbyte/helm/airbyte/charts/postgres-0.1.16.tgz
  airbyte/helm/airbyte/values.yaml
Labels: enhancement

#476 Support BYOK for aws EKS
  bootstrap/helm/bootstrap/Chart.yaml
  bootstrap/helm/bootstrap/values.yaml
  bootstrap/helm/bootstrap/values.yaml.tpl
  bootstrap/terraform/aws-bootstrap/aws-lb-controller.tf
  bootstrap/terraform/aws-bootstrap/certmanager.tf
  bootstrap/terraform/aws-bootstrap/data.tf
  bootstrap/terraform/aws-bootstrap/ebs-csi-driver.tf
  bootstrap/terraform/aws-bootstrap/existing.tf
  bootstrap/terraform/aws-bootstrap/irsa-autoscaler.tf
  bootstrap/terraform/aws-bootstrap/irsa-externaldns.tf
  bootstrap/terraform/aws-bootstrap/irsa.tf
  bootstrap/terraform/aws-bootstrap/locals.tf
  bootstrap/terraform/aws-bootstrap/main.tf
  bootstrap/terraform/aws-bootstrap/output.tf
  bootstrap/terraform/aws-bootstrap/s3-vpc-endpoint.tf
  bootstrap/terraform/aws-bootstrap/terraform.tfvars
  bootstrap/terraform/aws-bootstrap/variables.tf
  bootstrap/terraform/aws-efs/main.tf
Labels: enhancement

#493 Update prefect to 2.7.9
  prefect/helm/prefect/Chart.lock
  prefect/helm/prefect/Chart.yaml
  prefect/helm/prefect/charts/prefect-agent-2022.11.11.tgz
  prefect/helm/prefect/charts/prefect-agent-2023.1.20.tgz
  prefect/helm/prefect/charts/prefect-orion-2022.11.11.tgz
  prefect/helm/prefect/charts/prefect-orion-2023.1.20.tgz
  prefect/helm/prefect/values.yaml
Labels: enhancement

#495 Fix prefect postgres password setup
  prefect/helm/prefect/Chart.yaml
  prefect/helm/prefect/values.yaml.tpl
Labels: bug

#501 Make cert-manager disable-able
  bootstrap/helm/bootstrap/Chart.yaml
  bootstrap/helm/bootstrap/templates/issuer.yaml
  bootstrap/helm/bootstrap/values.yaml
Labels: enhancement

#503 Add oidc notes for airbyte + dagster
  airbyte/plural/notes.tpl
  dagster/plural/notes.tpl
Labels: enhancement

#504 Onboard standalone prefect agent
  prefect-agent/Pluralfile
  prefect-agent/helm/prefect-agent/.helmignore
  prefect-agent/helm/prefect-agent/Chart.lock
  prefect-agent/helm/prefect-agent/Chart.yaml
  prefect-agent/helm/prefect-agent/README.md
  prefect-agent/helm/prefect-agent/charts/prefect-agent-2023.1.20.tgz
  prefect-agent/helm/prefect-agent/charts/test-base-0.1.3.tgz
  prefect-agent/helm/prefect-agent/deps.yaml
  prefect-agent/helm/prefect-agent/runbooks/scaling-manual.xml
  prefect-agent/helm/prefect-agent/templates/runbooks.yaml
  prefect-agent/helm/prefect-agent/templates/secret.yaml
  prefect-agent/helm/prefect-agent/values.yaml
  prefect-agent/helm/prefect-agent/values.yaml.tpl
  prefect-agent/plural/icons/prefect.png
  prefect-agent/plural/notes.tpl
  prefect-agent/plural/recipes/prefect-agent-aws.yaml
  prefect-agent/plural/recipes/prefect-agent-azure.yaml
  prefect-agent/plural/recipes/prefect-agent-gcp.yaml
  prefect-agent/repository.yaml
  prefect-agent/terraform/kube/deps.yaml
  prefect-agent/terraform/kube/main.tf
  prefect-agent/terraform/kube/terraform.tfvars
  prefect-agent/terraform/kube/variables.tf
  prefect/helm/prefect/Chart.lock
  prefect/helm/prefect/Chart.yaml
  prefect/helm/prefect/charts/test-base-0.1.3.tgz
  prefect/helm/prefect/values.yaml
Labels: enhancement

#481 chore(ray): update aws node groups to k8s 1.22
  ray/terraform/aws/deps.yaml
  ray/terraform/aws/main.tf
  ray/terraform/aws/variables.tf
Labels: dependencies, hotfix

#510 update spark operator for k8s 1.22
  spark/helm/spark/Chart.lock
  spark/helm/spark/Chart.yaml
  spark/helm/spark/charts/spark-operator-1.1.26.tgz
  spark/helm/spark/charts/spark-operator-1.1.9.tgz
  spark/helm/spark/values.yaml
  spark/vendor_images.yaml
Labels: dependencies, hotfix
