Repository pluralsh/plural-artifacts, pull requests merged in 2023-02, with the labels that each got.

#514 Bump superset pool size
  superset/helm/superset/Chart.yaml
  superset/helm/superset/values.yaml
Labels: enhancement

#517 Stabilize n8n encryption key
  n8n/helm/n8n/Chart.yaml
  n8n/helm/n8n/templates/deployment.yaml
  n8n/helm/n8n/templates/secret.yaml
  n8n/helm/n8n/values.yaml
  n8n/helm/n8n/values.yaml.tpl
Labels: bug

#515 Extend airbyte oauth2-proxy timeout
  airbyte/helm/airbyte/Chart.yaml
  airbyte/helm/airbyte/values.yaml
  bin/rand_csv.py
  bin/requirements.txt
Labels: bug

#519 Fix datadog azure integration
  datadog/helm/datadog/Chart.lock
  datadog/helm/datadog/Chart.yaml
  datadog/helm/datadog/charts/config-overlays-0.1.1.tgz
  datadog/helm/datadog/values.yaml
  datadog/helm/datadog/values.yaml.tpl
Labels: enhancement

#520 Bump datahub frontend limit
  datahub/helm/datahub/Chart.yaml
  datahub/helm/datahub/values.yaml
Labels: bug

#522 Fix aws loadbalancer iam policy
  bootstrap/terraform/aws-bootstrap/aws-lb-controller.tf
  bootstrap/terraform/aws-bootstrap/deps.yaml
Labels: bug

#524 fix(ray): allows for changing the instance type
  ray/terraform/aws/deps.yaml
  ray/terraform/aws/main.tf
Labels: hotfix

#523 Add docs for configuring trino catalogs
  airflow/helm/airflow/Chart.yaml
  airflow/helm/airflow/templates/statsd-exporter.yaml
  airflow/helm/airflow/values.yaml
  airflow/vendor_images.yaml
  trino/plural/docs/adding-catalogs.md
  trino/repository.yaml
Labels: documentation

#527 Disable aks monitoring by default
  airflow/helm/airflow/Chart.yaml
  airflow/helm/airflow/values.yaml
  bootstrap/helm/azure-identity/Chart.yaml
  bootstrap/helm/azure-identity/templates/tests/test-connection.yaml
  bootstrap/helm/azure-identity/values.yaml
  bootstrap/terraform/azure-bootstrap/deps.yaml
  bootstrap/terraform/azure-bootstrap/main.tf
  bootstrap/terraform/azure-bootstrap/variables.tf
  monitoring/helm/monitoring/Chart.yaml
  monitoring/helm/monitoring/values.yaml
  n8n/helm/n8n/Chart.yaml
  n8n/helm/n8n/templates/deployment.yaml
  n8n/helm/n8n/values.yaml
Labels: bug

#530 Disable opentelemetry
  monitoring/helm/monitoring/Chart.yaml
  monitoring/helm/monitoring/values.yaml
Labels: bug

#532 remove namespace alert label
  monitoring/helm/monitoring/Chart.yaml
  monitoring/helm/monitoring/values.yaml
Labels: bug

#533 Fix gitlab on gcp+azure
  airbyte/helm/airbyte/Chart.yaml
  airbyte/helm/airbyte/values.yaml
  airbyte/plural/docs/basic-auth.md
  airbyte/plural/docs/bring-your-own-db.md
  airflow/plural/docs/bring-your-db.md
  airflow/plural/docs/pip-packages.md
  gitlab/terraform/azure/deps.yaml
  gitlab/terraform/azure/main.tf
  gitlab/terraform/azure/outputs.tf
  gitlab/terraform/gcp/deps.yaml
  superset/plural/docs/pip-packages.md
  valheim/helm/valheim/Chart.yaml
Labels: bug
