Repository pluralsh/plural-artifacts, pull requests merged in 2023-04, with the labels that each got.

#621 Fix loki templating
  loki/helm/loki/Chart.yaml
  loki/helm/loki/values.yaml.tpl
Labels: bug

#623 feat(elasticsearch): improve post install notes
  elasticsearch/plural/notes.tpl
Labels: documentation, enhancement

#631 docs: Add External contributor flow docs
  .github/workflows/matrix-vendor-and-publish.yml
  README.md
  baserow/plural/recipes/baserow-aws.yaml
  baserow/plural/recipes/baserow-azure.yaml
  baserow/plural/recipes/baserow-gcp.yaml
  dagster-agent/repository.yaml
  dagster/helm/dagster/Chart.yaml
  dagster/helm/dagster/values.yaml
  jenkins/plural/recipes/jenkins-aws.yaml
  jenkins/plural/recipes/jenkins-azure.yaml
  jenkins/plural/recipes/jenkins-gcp.yaml
  jupyterhub/plural/recipes/jupyterhub-aws.yaml
  jupyterhub/plural/recipes/jupyterhub-azure.yaml
  jupyterhub/plural/recipes/jupyterhub-gcp.yaml
  tier/plural/recipes/tier-aws.yaml
  tier/plural/recipes/tier-azure.yaml
  tier/plural/recipes/tier-gcp.yaml
Labels: documentation

#627 feat: Fix jupyterhub notes and add oidc auth
  jupyterhub/helm/jupyterhub/values.yaml.tpl
  jupyterhub/plural/notes.tpl
  jupyterhub/plural/recipes/jupyterhub-aws.yaml
  jupyterhub/plural/recipes/jupyterhub-azure.yaml
  jupyterhub/plural/recipes/jupyterhub-gcp.yaml
  jupyterhub/repository.yaml
Labels: enhancement

#635 feat: Jupyterhub OIDC + Cleanup
  jupyterhub/helm/jupyterhub/Chart.lock
  jupyterhub/helm/jupyterhub/Chart.yaml
  jupyterhub/helm/jupyterhub/charts/jupyterhub-2.0.0.tgz
  jupyterhub/helm/jupyterhub/charts/jupyterhub-3.0.12.tgz
  jupyterhub/helm/jupyterhub/charts/postgres-0.1.16.tgz
  jupyterhub/helm/jupyterhub/templates/_helpers.tpl
  jupyterhub/helm/jupyterhub/templates/runbooks.yaml
  jupyterhub/helm/jupyterhub/templates/secret.yaml
  jupyterhub/helm/jupyterhub/values.yaml
  jupyterhub/helm/jupyterhub/values.yaml.tpl
  jupyterhub/plural/notes.tpl
  jupyterhub/plural/recipes/jupyterhub-aws.yaml
  jupyterhub/plural/recipes/jupyterhub-azure.yaml
  jupyterhub/plural/recipes/jupyterhub-gcp.yaml
  jupyterhub/repository.yaml
  jupyterhub/vendor_images.yaml
Labels: enhancement

#640 feat: Add tags to azure resources
  bootstrap/terraform/azure-bootstrap/deps.yaml
  bootstrap/terraform/azure-bootstrap/main.tf
  bootstrap/terraform/azure-bootstrap/variables.tf
Labels: enhancement

#644 feat: Bootstrap operator
  bootstrap/helm/bootstrap-operator/.helmignore
  bootstrap/helm/bootstrap-operator/Chart.yaml
  bootstrap/helm/bootstrap-operator/README.md
  bootstrap/helm/bootstrap-operator/crds/bootstrap.plural.sh_bootstraps.yaml
  bootstrap/helm/bootstrap-operator/crds/bootstrapproviders.operator.cluster.x-k8s.io.yaml
  bootstrap/helm/bootstrap-operator/crds/controlplaneproviders.operator.cluster.x-k8s.io.yaml
  bootstrap/helm/bootstrap-operator/crds/coreproviders.operator.cluster.x-k8s.io.yaml
  bootstrap/helm/bootstrap-operator/crds/nfrastructureproviders.operator.cluster.x-k8s.io.yaml
  bootstrap/helm/bootstrap-operator/templates/_helpers.tpl
  bootstrap/helm/bootstrap-operator/templates/bootstrap.yaml
  bootstrap/helm/bootstrap-operator/templates/clusterrole.yaml
  bootstrap/helm/bootstrap-operator/templates/clusterrolebinding.yaml
  bootstrap/helm/bootstrap-operator/templates/controller-deployment.yaml
  bootstrap/helm/bootstrap-operator/templates/secret.yaml
  bootstrap/helm/bootstrap-operator/templates/serviceaccount.yaml
  bootstrap/helm/bootstrap-operator/values.yaml
  bootstrap/helm/bootstrap-operator/values.yaml.tpl
  bootstrap/plural/recipes/aws-cluster-api.yaml
  bootstrap/terraform/aws-bootstrap-cluster-api/main.tf
  bootstrap/terraform/aws-bootstrap-cluster-api/terraform.tfvars
  bootstrap/terraform/aws-bootstrap-cluster-api/variables.tf
Labels: enhancement

#656 feat: Upgrade n8n to use upstream chart
  n8n/helm/n8n/Chart.lock
  n8n/helm/n8n/Chart.yaml
  n8n/helm/n8n/charts/n8n-0.10.0.tgz
  n8n/helm/n8n/charts/postgres-0.1.10.tgz
  n8n/helm/n8n/charts/postgres-0.1.17.tgz
  n8n/helm/n8n/charts/redis-17.9.5.tgz
  n8n/helm/n8n/templates/NOTES.txt
  n8n/helm/n8n/templates/_helpers.tpl
  n8n/helm/n8n/templates/deployment.yaml
  n8n/helm/n8n/templates/ingress.yaml
  n8n/helm/n8n/templates/service.yaml
  n8n/helm/n8n/templates/serviceaccount.yaml
  n8n/helm/n8n/values.yaml
  n8n/helm/n8n/values.yaml.tpl
Labels: enhancement

#659 Add contributor program details
  README.md
Labels: documentation

#668 feat: Support mimir basic auth
  grafana/plural/docs/plugins.md
  grafana/repository.yaml
  mimir/helm/mimir/Chart.yaml
  mimir/helm/mimir/templates/basic-auth.yaml
  mimir/helm/mimir/values.yaml
  mimir/helm/mimir/values.yaml.tpl
  mimir/plural/docs/external-access.md
  mimir/plural/icons/mimir.png
  mimir/repository.yaml
Labels: enhancement

#674 feat: Bake n8n scaling runbook
  n8n/helm/n8n/Chart.yaml
  n8n/helm/n8n/runbooks/scaling-manual.xml
  n8n/helm/n8n/templates/runbook.yaml
Labels: enhancement

#670 feat: Enable dagster in-chart migrations
  dagster/helm/dagster/Chart.yaml
  dagster/helm/dagster/values.yaml
Labels: enhancement
